//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Allocation id invalid.&apos;.
        /// </summary>
        public static string AllocationIdInvalid {
            get {
                return ResourceManager.GetString("AllocationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee already allocated to this project.&apos;.
        /// </summary>
        public static string EmployeeAlreadyOnProject {
            get {
                return ResourceManager.GetString("EmployeeAlreadyOnProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee does not have enough unallocated time.&apos;.
        /// </summary>
        public static string EmployeeFreeTimeNotEnough {
            get {
                return ResourceManager.GetString("EmployeeFreeTimeNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Invalid employee id&apos;.
        /// </summary>
        public static string EmployeeIdInvalid {
            get {
                return ResourceManager.GetString("EmployeeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding allocation:&apos;.
        /// </summary>
        public static string ErrorWhileAddingAllocation {
            get {
                return ResourceManager.GetString("ErrorWhileAddingAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department already exist in this office&apos;.
        /// </summary>
        public static string ErrorWhileAddingDepartment {
            get {
                return ResourceManager.GetString("ErrorWhileAddingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be added: Name field is empty.&apos;.
        /// </summary>
        public static string ErrorWhileAddingDepartment_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileAddingDepartment_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be updated: Name too long.&apos;.
        /// </summary>
        public static string ErrorWhileAddingDepartment_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileAddingDepartment_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be added: OfficeId invalid.&apos;.
        /// </summary>
        public static string ErrorWhileAddingDepartment_OfficeIdInvalid {
            get {
                return ResourceManager.GetString("ErrorWhileAddingDepartment_OfficeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Empty employee name.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_EmptyEmployeeName {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_EmptyEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Cannot have a negative number of employment hours.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_NegativeEmploymentHours {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NegativeEmploymentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding employee: No such department has been found..
        /// </summary>
        public static string ErrorWhileAddingEmployee_NoSuchDepartment {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NoSuchDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding employee: No such position has been found..
        /// </summary>
        public static string ErrorWhileAddingEmployee_NoSuchPosition {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NoSuchPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding employee: DepartmentId cannot be null..
        /// </summary>
        public static string ErrorWhileAddingEmployee_NullDepartmentId {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NullDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Cannot have null EmploymentDate.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_NullEmploymentDate {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NullEmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding employee: PositionId cannot be null..
        /// </summary>
        public static string ErrorWhileAddingEmployee_NullPositionId {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_NullPositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Too long employee address.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_TooLongEmployeeAddress {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_TooLongEmployeeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Too long e-mail address.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_TooLongEmployeeEmail {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_TooLongEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee: Employee name too long. &apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_TooLongEmployeeName {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_TooLongEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding employee; Cannot have a number of employment hours greater than 8.&apos;.
        /// </summary>
        public static string ErrorWhileAddingEmployee_TooManyHours {
            get {
                return ResourceManager.GetString("ErrorWhileAddingEmployee_TooManyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Address too long.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_AddressTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_AddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Address fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_EmptyAddress {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Name fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Phone fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_EmptyPhone {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_EmptyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Name too long.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be added: Phone too long.&apos;.
        /// </summary>
        public static string ErrorWhileAddingOffice_PhoneTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileAddingOffice_PhoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position could not be added: Name field is empty.&apos;.
        /// </summary>
        public static string ErrorWhileAddingPosition_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileAddingPosition_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position could not be updated: Name too long.&apos;.
        /// </summary>
        public static string ErrorWhileAddingPosition_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileAddingPosition_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding project.&apos;.
        /// </summary>
        public static string ErrorWhileAddingProject {
            get {
                return ResourceManager.GetString("ErrorWhileAddingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while adding project, department invalid id.&apos;.
        /// </summary>
        public static string ErrorWhileAddingProject_DepartmentIdInvalid {
            get {
                return ResourceManager.GetString("ErrorWhileAddingProject_DepartmentIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while deleting allocation.&apos;.
        /// </summary>
        public static string ErrorWhileDeleteingAllocation {
            get {
                return ResourceManager.GetString("ErrorWhileDeleteingAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project coud not be deleted.&apos;.
        /// </summary>
        public static string ErrorWhileDeletingProject {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee does not exist&apos;.
        /// </summary>
        public static string ErrorWhileReleasingEmployee {
            get {
                return ResourceManager.GetString("ErrorWhileReleasingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating allocation:&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingAllocation {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department could not be updated: Name field is empty..
        /// </summary>
        public static string ErrorWhileUpdatingDepartment_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingDepartment_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be modified: Invalid department id&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingDepartment_InvalidId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingDepartment_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department could not be updated: Name too long..
        /// </summary>
        public static string ErrorWhileUpdatingDepartment_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingDepartment_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be updated: OfficeId invalid.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingDepartment_OfficeIdInvalid {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingDepartment_OfficeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Empty employee name.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_EmptyEmployeeName {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_EmptyEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Invalid employee Id.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_InvalidId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Negative employment hours.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_NegativeEmploymentHours {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_NegativeEmploymentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating employee: DepartmentId cannot be null..
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_NullDepartmentId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_NullDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Null employment date.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_NullEmploymentDate {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_NullEmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating employee: PositionId cannot be null..
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_NullPositionId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_NullPositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Too long employee address.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_TooLongEmployeeAddress {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_TooLongEmployeeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Too long employee e-mail.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_TooLongEmployeeEmail {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_TooLongEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Too long employee name.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_TooLongEmployeeName {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_TooLongEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating employee: Too many employment hours.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee_TooManyHours {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee_TooManyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated: Address too long.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_AddressTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_AddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated Address fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_EmptyAddress {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated Name fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated Phone fied is empty.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_EmptyPhone {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_EmptyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating office: Invalid id&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_InvalidId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated: Name too long.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be updated: Phone too long.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice_PhoneTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice_PhoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position could not be modified.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingPosition {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position could not be modified: Name field is empty.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingPosition_EmptyName {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPosition_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating position: Invalid id&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingPosition_InvalidId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPosition_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position could not be modified: Name too long.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingPosition_NameTooLong {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPosition_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updatign project.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingProject {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating project, department invalid id.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingProject_DepartmentIdInvalid {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingProject_DepartmentIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Error while updating project, invalid project id.&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingProject_InvalidId {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingProject_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Invalid project id.&apos;.
        /// </summary>
        public static string ProjectInvalidId {
            get {
                return ResourceManager.GetString("ProjectInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project name is empty.&apos;.
        /// </summary>
        public static string ProjectNameEmpty {
            get {
                return ResourceManager.GetString("ProjectNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project name is too long.&apos;.
        /// </summary>
        public static string ProjectNameTooLong {
            get {
                return ResourceManager.GetString("ProjectNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project status is empty.&apos;.
        /// </summary>
        public static string ProjectStatusEmpty {
            get {
                return ResourceManager.GetString("ProjectStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project status is too long.&apos;.
        /// </summary>
        public static string ProjectStatusTooLong {
            get {
                return ResourceManager.GetString("ProjectStatusTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Allocation added successfully.&apos;.
        /// </summary>
        public static string SuccessfullyAddedAllocation {
            get {
                return ResourceManager.GetString("SuccessfullyAddedAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedDepartment {
            get {
                return ResourceManager.GetString("SuccessfullyAddedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was added with success.&apos;.
        /// </summary>
        public static string SuccessfullyAddedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyAddedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedOffice {
            get {
                return ResourceManager.GetString("SuccessfullyAddedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedPosition {
            get {
                return ResourceManager.GetString("SuccessfullyAddedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Successfully added project.&apos;.
        /// </summary>
        public static string SuccessfullyAddedProject {
            get {
                return ResourceManager.GetString("SuccessfullyAddedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Successfully deleted allocation.&apos;.
        /// </summary>
        public static string SuccessfullyDeletedAllocation {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Successfully deleted project.&apos;.
        /// </summary>
        public static string SuccessfullyDeletedProject {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was released with success&apos;.
        /// </summary>
        public static string SuccessfullyReleasedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyReleasedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Successfully updated allocation&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedAllocation {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedDepartment {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Successfully updated employee.&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedOffice {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Position was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedPosition {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Succsessfully updated project.&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedProject {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedProject", resourceCulture);
            }
        }
    }
}
