//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be deleted&apos;.
        /// </summary>
        public static string ErrorWhileDeletingDepartment {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee could not be deleted&apos;.
        /// </summary>
        public static string ErrorWhileDeletingEmployee {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee could not be deleted from Project&apos;.
        /// </summary>
        public static string ErrorWhileDeletingEmployeeFromProject {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingEmployeeFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be deleted&apos;.
        /// </summary>
        public static string ErrorWhileDeletingOffice {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project could not be deleted&apos;.
        /// </summary>
        public static string ErrorWhileDeletingProject {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Allocation could not be modified&apos;.
        /// </summary>
        public static string ErrorWhileEditingAllocation {
            get {
                return ResourceManager.GetString("ErrorWhileEditingAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department could not be modified&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingDepartment {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee could not be modified&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingEmployee {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office could not be modified&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingOffice {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project could not be modified&apos;.
        /// </summary>
        public static string ErrorWhileUpdatingProject {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedDepartment {
            get {
                return ResourceManager.GetString("SuccessfullyAddedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyAddedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Assignment was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedNewAssignment {
            get {
                return ResourceManager.GetString("SuccessfullyAddedNewAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedOffice {
            get {
                return ResourceManager.GetString("SuccessfullyAddedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project was added with success&apos;.
        /// </summary>
        public static string SuccessfullyAddedProject {
            get {
                return ResourceManager.GetString("SuccessfullyAddedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department was deleted with success&apos;.
        /// </summary>
        public static string SuccessfullyDeletedDepartment {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was deleted successfully&apos;.
        /// </summary>
        public static string SuccessfullyDeletedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was deleted from Project with success&apos;.
        /// </summary>
        public static string SuccessfullyDeletedEmployeeFromProject {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedEmployeeFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office was deleted with success&apos;.
        /// </summary>
        public static string SuccessfullyDeletedOffice {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project was deleted successfully&apos;.
        /// </summary>
        public static string SuccessfullyDeletedProject {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Allocation was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyEditedAllocation {
            get {
                return ResourceManager.GetString("SuccessfullyEditedAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Department was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedDepartment {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Office was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedOffice {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Project was updated with success&apos;.
        /// </summary>
        public static string SuccessfullyUpdatedProject {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedProject", resourceCulture);
            }
        }
    }
}
